#spring:

# Path of the main dispatcher servlet
server:
  servlet:
    contextPath: /api/v1.0
#    servlet-path: /api/v1.0
  port: 9004

location: upload-dir

#spring.http.multipart.max-file-size: 128KB
#spring.http.multipart.max-request-size: 128KB